# find gmock library
#   GMOCK_LIB     [out]         Link to these to use the gmock library

SET (GMOCK_LIB_NAME gmock)

FIND_LIBRARY (GMOCK_LIB NAMES ${GMOCK_LIB_NAME} PATHS $ENV{PATH} ${ADDITIONAL_LIB_PATH})
SET (GMOCK_LIB_ONLYNAME ${GMOCK_LIB_NAME})

IF (GMOCK_LIB)
	SET (GMOCK_FOUND YES)
ELSE (GMOCK_LIB)
	SET (GMOCK_LIB "")
	SET (GMOCK_FOUND NO)
ENDIF (GMOCK_LIB)
